version: '3.4'
services:
#  Optional
#  content-extractor-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: content-extractor-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  content-extractor-acs:
    image: alfresco-content-services-content-extractor:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dmessaging.broker.url=\"failover:(nio://content-extractor-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - content-extractor-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - content-extractor-postgres
  content-extractor-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - content-extractor-db-volume:/var/lib/postgresql/data
  content-extractor-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: content-extractor-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: content-extractor-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - content-extractor-ass-volume:/opt/alfresco-search-services/contentstore
      - content-extractor-ass-volume:/opt/alfresco-search-services/data
  content-extractor-activemq:
      image: alfresco/alfresco-activemq:5.16.1
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  content-extractor-acs-volume:
    external: true
  content-extractor-db-volume:
    external: true
  content-extractor-ass-volume:
    external: true
